### ISSUE TITLE
Failed to start discovery with Google Play services 23.34.14

### ISSUE THREAD

**Issue by maciejkrolik** [google/nearby#2124]
### Project

Nearby Connections

### Language

Kotlin

### OS Platform

Android (com.google.android.gms:play-services-nearby:18.7.0)

### What happened?

With Google Play services 23.34.14 I get attached error every time I call startDiscovery. It doesn't matter which strategy I choose. With older version of Google Play services everything works as expected. Tested e.g. on 22.06.18. 

Issue can be reproduced on different phones (OnePlus 6 - Android 11, Samsung S20 FE - Android 12, Samsung A21s - Android 11).

### What did you expect to happen?

Nearby Connections should start discovery successfully on the latest version of Google Play services

### How can we reproduce it (as minimally and precisely as possible)?

1. Call startDiscovery method on a phone with Google Play services 23.34.14 installed

### How often does this bug happen?

Every time

### Relevant log output

```shell
Failed to start discovery.
                                                                                                    com.google.android.gms.common.api.ApiException: 17: API: Nearby.CONNECTIONS_API is not available on this device. Connection failed with: ConnectionResult{statusCode=INTERNAL_ERROR, resolution=null, message=null}
                                                                                                    	at com.google.android.gms.common.api.internal.zad.zad(com.google.android.gms:play-services-base@@18.0.1:1)
                                                                                                    	at com.google.android.gms.common.api.internal.zabq.zaE(com.google.android.gms:play-services-base@@18.0.1:7)
                                                                                                    	at com.google.android.gms.common.api.internal.zabq.zaD(com.google.android.gms:play-services-base@@18.0.1:2)
                                                                                                    	at com.google.android.gms.common.api.internal.zabq.zar(com.google.android.gms:play-services-base@@18.0.1:24)
                                                                                                    	at com.google.android.gms.common.api.internal.zabq.onConnectionFailed(com.google.android.gms:play-services-base@@18.0.1:1)
                                                                                                    	at com.google.android.gms.common.internal.zai.onConnectionFailed(com.google.android.gms:play-services-base@@18.0.1:1)
                                                                                                    	at com.google.android.gms.common.internal.zzf.zzb(com.google.android.gms:play-services-basement@@18.1.0:2)
                                                                                                    	at com.google.android.gms.common.internal.zza.zza(com.google.android.gms:play-services-basement@@18.1.0:3)
                                                                                                    	at com.google.android.gms.common.internal.zzc.zze(com.google.android.gms:play-services-basement@@18.1.0:3)
                                                                                                    	at com.google.android.gms.common.internal.zzb.handleMessage(com.google.android.gms:play-services-basement@@18.1.0:31)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Anything else we need to know?

startAdvertising method works as expected

**Comment by bourdakos1** [comment]
@Xlythe can you take a look?

**Comment by Xlythe** [comment]
We found & fixed the issue, but we need to push an update to Google Play services and that'll take some time. If you use an older version of the SDK, does it work?

**Comment by maciejkrolik** [comment]
Thanks! Yes, it works with older versions

**Comment by huynhj02** [comment]
> Thanks! Yes, it works with older versions

Sorry, how did you change the SDK for the service? would it just be changing the dependency implementation version
`com.google.android.gms:play-services-nearby:18.5.0` as it seems like it's google-play-services and not specifically play-services-nearby.

**Comment by maciejkrolik** [comment]
@huynhj02 I'm sorry, maybe I misunderstood the initial question. For me, it works only with older versions of Google Play services. With an older version of the Play Services Nearby (e.g. 18.5.0) it still doesn't work :(

**Comment by huynhj02** [comment]
That makes sense to me, thank you! Just wondering how you changed your Google Play services to an older version?

**Comment by maciejkrolik** [comment]
@huynhj02 I did it by going to Settings -> Apps -> Google Play services. Then tap on the three dots in the top right corner and choose "Uninstall updates"

**Comment by rstewart22** [comment]
@Xlythe an approximate ETA on new Google Play Services update, would be really apprecated - days... or weeks?

**Comment by cazterk** [comment]
Hope it gets fixed soon because it breaks functionality

**Comment by xiangjun-z** [comment]
If your product is impacted, please follow the instruction [here](https://b.corp.google.com/issues/299170799#comment46). 
If your affected App is in US play store, please email me your play store link. Otherwise, you can send me your APK.

**Comment by SherwinDeveloper** [comment]
https://play.google.com/store/apps/details?id=com.appshive.just_bills

**Comment by KRA2008** [comment]
@xiangjun-z is that link correct? it seems like it's behind some authentication i can't get through.

**Comment by KRA2008** [comment]
I guess I don't need the instructions because I'm in the US Google Play Store. Please add an exception for my app:

https://play.google.com/store/apps/details?id=com.kra2008.crosscam

**Comment by rausanka** [comment]
Here are the details (first bullet is the instructions to be immediately allow listed while we roll out the fix:

1. Please send your APK (or the build fingerprint for your APK or package name if you distribute through the US Play Store) to us so we can add your app to an allow list that will immediately work around the issue – [instructions on retrieving a build fingerprint](https://developer.squareup.com/docs/pos-api/cookbook/find-your-android-fingerprint). We'll need this for each APK signed by a different certificate.
2. We are cherry-picking a rollback into the current version of Play Services that is rolling out to 100% next Monday, September 25
3. A proper fix will roll out in Play Services 100% on October 4

**Comment by xiangjun-z** [comment]
com.appshive.just_bills and com.kra2008.crosscam are added to our allowlist. Please allow up to 2 hours for it to propagate.

**Comment by xiangjun-z** [comment]
If your development is blocked by this issue, you can join our play service beta: https://play.google.com/apps/testing/com.google.android.gms We are rolling out a fix in the beta version.

**Comment by mshedeed-wf** [comment]
@xiangjun-z Hello, could you add our app's fingerprint to the whitelist:
`SHA1: AF:8C:39:12:D9:83:40:A9:F1:69:61:BD:E9:5B:4F:09:CF:B4:6C:27`

**Comment by xiangjun-z** [comment]
@mshedeed-wf  Please let us know the package name of your App.

**Comment by mshedeed-wf** [comment]
> @mshedeed-wf Please let us know the package name of your App.

@xiangjun-z of course, here you go:
`com.waveform.walk_test`

**Comment by xiangjun-z** [comment]
@mshedeed-wf The App has been allowlisted last Friday. Would you please check if it works now?

**Comment by mshedeed-wf** [comment]
@xiangjun-z unfortunately it's still not working :/ Can you please advise? We're in a middle of a critical testing phase with potential clients. 

https://play.google.com/store/apps/details?id=com.waveform.walk_test

It's available in closed testing track

**Comment by xiangjun-z** [comment]
@mshedeed-wf  If it's during test phase, I wonder if you switch to playstore beta channel?

https://play.google.com/apps/testing/com.google.android.gms

Also, you can try to reboot your Android 10 devices.

**Comment by mshedeed-wf** [comment]
@xiangjun-z The latest beta (released on 21/9) still has the bug, I tried rebooting all devices. Is there any timeline on when this is going to be fixed? Thanks 🙏

**Comment by fefox74** [comment]
@xiangjun-z do you when is nearby going to start working on all devices?

**Comment by cazterk** [comment]
Works for me now

**Comment by xiangjun-z** [comment]
The fix has been rolled out in PlayService W36.

**Comment by fiasko131** [comment]
@xiangjun-z  
You announced the deployment of an update with the fix for October 4, is this still current?
At the moment no update in sight for me.
THANKS

**Comment by xiangjun-z** [comment]
@fiasko131 The fix has been rolled out on 2023W36 release. I wonder if you have checked your play service version?
If it doesn't work, please try to uninstall update of Google Play Services then update again.

Play Services should be automatically updated on most devices.
